clear all
close all

cd "/home/mvb/0_ETH/MasterThesis/Logs_GoKart/LogData/20190310";

filename = "20190310T195505_00.mat";

load(filename);
gokartData = postProcessData(gokartData);
printf("Data postprocessed.\n")
timeNames = [...
            "gokartData.steerTorque.command.time";...
            "gokartData.steerPosition.calibrated.time";...
            "gokartData.poseSmooth.x.time";...
            "gokartData.linmotPosition.command.time";...
            "gokartData.linmotPosition.effective.time";...
            "gokartData.rimoTorqueCommand.left.time";...
            "gokartData.rimoRotationalRate.left.time";...
            "gokartData.vmu931.xdtdt.time";...
            "gokartData.vmu931Filtered.xdtdtds.time"...
            ]
samplingTime = zeros(size(timeNames)(1),1);
for i = 1 : size(timeNames)(1)
  time = eval(timeNames(i,:));
  samplingTime(i) = (time(end) - time(1))/length(time);
%  samplingTime(i) = (time(500) - time(499));
endfor
timeNames
samplingTime