version: 2
workflows:
  version: 2
  test:
    jobs:
      - kartsim-test-3.7
      - kartsim-test-3.6
      - kartsim-test-3.5
jobs:
  kartsim-test-3.6: &test-template
    docker:
      - image: python3.6
    steps:
      - checkout
      - run:
          name: Install deps
          working_directory: .
          command: |
            pip3 install --user --upgrade -r requirements.txt
            python3 setup.py develop --user --no-deps
      - run:
          name: Run tests
          working_directory: .
          environment:
            DISABLE_CONTRACTS: 1
          command: |
            python3 -m unittest discover -s ./tests -p "*_test.py"

  kartsim-test-3.7: *test-template
    docker:
      - image: python:3.7
  kartsim-test-3.5: *test-template
    docker:
      - image: python:3.5